### PR TITLE
[Clean-up] Remove GET_ACCOUNTS permission

### PR DESCRIPTION
**Pull request by thomashorta**
Internal reference: p8Qyks-6RS-p2#comment-2782
WordPress-Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/19076

This cleans up an unused util class that required a dangerous permission that is caught by Google Play Store's scans and reviews (`GET_ACCOUNTS`) so we should avoid declaring it unless we really use it.

This could be the cause of recent Google Play rejections regarding "Contacts" permissions as it causes a "Contacts Permission" item to show up in the app info's permission list.

image

### CODE REVIEW

**Comment by RenanLukas** [comment]
Thanks for the PR, @thomashorta !

Is it worth to have an internal announcement about this change in the library? I see, for example, that `woocommerce-android` [has this library](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/build.gradle#L230), but couldn't find any specific reference to the removed class. I wonder if other products are using it, though 🤔

**Review by guarani — APPROVED** [review]
I tested this via https://github.com/wordpress-mobile/WordPress-Android/pull/19076#pullrequestreview-1596378911. I'll defer to an Android dev to review the code but it seems to work great.

Thanks @thomashorta!

**Review by RenanLukas — APPROVED** [review]
Tested in https://github.com/wordpress-mobile/WordPress-Android/pull/19076. LGTM :shipit:

**Comment by ravishanker** [comment]
> Thanks for the PR, @thomashorta !
> 
> Is it worth to have an internal announcement about this change in the library? I see, for example, that `woocommerce-android` [has this library](https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/build.gradle#L230), but couldn't find any specific reference to the removed class. I wonder if other products are using it, though 🤔

Posted a summary on P2 pbArwn-6dO-p2
Feel free to update it if required.  Thank you

**Pull request merged**
