### PR TITLE
Update README to 1.40.0

### PR DESCRIPTION
**Pull request by oguzkocer**

### CODE REVIEW

**Review by mokagio — APPROVED** [review]

**Comment by mokagio** [comment]
We can safely ignore the Peril error.

**Comment by oguzkocer** [comment]
> Please update the library version before merging into `develop`

Hmm.. this error does not make sense anymore. Even if this PR included code changes, we don't use the version value for publishing the library, so I think we should get rid of this Peril check. We might even want to remove the [versionName](https://github.com/wordpress-mobile/WordPress-Utils-Android/blob/develop/WordPressUtils/build.gradle#L57) if we can or at least add a comment saying we don't use this number to make it clear to other developers.

What do you think @mokagio?

**Comment by mokagio** [comment]
Good point!

The previous workflow wasn't looking at the tag, but always reading from `versionName`. This one doesn't, and it's for the best as it gives us more flexibility.

**Comment by mokagio** [comment]
@oguzkocer followup regarding the `versionName` error from Peril:

- https://github.com/wordpress-mobile/WordPress-Utils-Android/pull/77
- https://github.com/Automattic/peril-settings/pull/70

**Pull request merged**
