### PR TITLE
[Build] Update Kotlin to 1.9.22

### PR DESCRIPTION
**Pull request by ParaskP7**
Required By: #148

This PR updates Kotlin to [1.9.22](https://github.com/JetBrains/kotlin/releases/tag/v1.9.22).

### Description

This update isn't that necessary, but should be considered anyway as it will do the following:
- Align this library, to that Kotlin version, which is already used by most of this library's clients and libraries.
- Unblock the usage of the [Dependency Analysis](https://github.com/autonomousapps/dependency-analysis-gradle-plugin) Gradle plugin for this project.
- Prepares this project for the Kotlin 2+ major update.

### Test

- There is nothing much to test here.
- Verifying that all the CI checks are successful should be enough.
- However, if you want to be thorough about reviewing this change, you could:
    - Quickly smoke test, either the [JP/WPAndroid](https://github.com/wordpress-mobile/WordPress-Android) and/or [WCAndroid](https://github.com/woocommerce/woocommerce-android) apps, with this version of `Utils`, or via composite builds, and see if it works as expected.
    - Test for build time increases (local & CI).

### CODE REVIEW

**Review by wzieba — APPROVED** [review]
Do you think it's worth to add dependency analysis to this project? It has a very little number of dependencies and is not actively developed.

This PR LGTM :+1:

**Comment by ParaskP7** [comment]
Just like we discussed the day before, I was indeed thinking about it @wzieba , but decided to go for it. I chose in the end to go for it because this library is used as composite build for at least JP/WPAndroid, used as a dependency on all, FluxC, JP/WPAndroid and WCAndroid, plus get some contribution here-and-there from time to time, and in general it has been discussed from time to time about properly supporting this library and not letting it be on it's own... 🤷 

-----

In the end, I think I decided to at least add `Dependency Analysis` to all the libraries that are at least used as composite builds for either JP/WPAndroid, WCAndroid, or both, those are:
- Login
- Utils
- Media Picker
- Aztec (+DOAndroid)
- About
- Tracks

I think for this initial phase of introducing the new `Dependency Analysis` process it would be enough to start with those 6 libraries and these 4 clients that we are already tracking:
- WCAndroid
- JP/WPAndroid
- DOAndroid
- PCAndroid

And with that, I think we can stop, gather some initial feedback on the overall end-to-end process and keep adding more clients/libraries when and if needed, on demand. Wdyt? 🤔

**Comment by ParaskP7** [comment]
> It has a very little number of dependencies...

I don't think this should matter too much, even one extra dependency or dependency misconfiguration can cause some trouble. Obviously, more of those could increase the risk of getting into trouble, but that doesn't mean having one of those there is risk, or at least maintenance free.

My goal with this plugin is to help us remove all those unused dependencies and then restrict each project to not allow any more unused dependencies from thereafter.

> ...and is not actively developed.

Btw, I think all those 6 libraries are (kind of) actively developed (from time to time), it is just that they are not being continuously developed.

**Comment by wzieba** [comment]
I don't see dependency-analysis-gradle-plugin printing anything troubling that could cause problems for projects that use the library, but if you think it's worth to keep such metrics for this and other libraries, I'm ok with it 👍

**Comment by ParaskP7** [comment]
Out of curiosity @wzieba , out of these 6 below libraries, where would you use the `Dependency Analysis` and why? This will help me understand how you are thinking about this plugin and its usefulness.

- Login
- Utils
- Media Picker
- Aztec (+DOAndroid)
- About
- Tracks

For example, for me, at this point, it is all about the maintainability of these libraries and me hoping that this plugin will give us advises that in time (when needed) will help us move forward, clean-up or fine-tune any dependencies.

**Comment by wzieba** [comment]
Frankly, I'd skip all the library projects (except FluxC due to its size and frequency of development). I think this plugin is very useful in case of large set of dependencies - removing unused dependencies and applying more fitting configurations can help in developer's experience.

I'm concerned that with the library projects that are developed rarely and are small, the difference we'll gain from improving dependency configuration will be minimal and metrics we'll get from them will be mostly flat line.

**Comment by ParaskP7** [comment]
Got it, thanks, I think that I now understand more where you're coming from (I agree). 💯 

To me, additional to your expectation(s):
- This plugin will provide the data for each of those libraries, the "build health" data, at least the "unused count" data initially, that we can act upon. Without this data being there, we would never know what can be done to improve a project build's health and why. 📉 
- Then, it will provide the mechanism to not allow deteriorating of the "build health" any further. For example, when you manage to remove all the unused dependencies, we can instruct the plugin to not allow any further unused dependencies into the projects any more. Then, any dev that removes some code, or update one feature with another, would need to also make sure to remove the unused dependency and not letting it hang there indefinitely. 🤞

**Pull request merged**
